### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by moenuma** [CMPUT301F21T03/Alpha-Apps#111]
- [x] Today page crashes after adding some habits (edit: @grapse fixed this in an upcoming push!)
- [x] AddHabit: when you make the habit 'public' and press "complete" button, (edit: somehow got fixed!)
- [x] AddHabit: you can add a habit without clicking any of the frequency checkboxes (edit: good catch! fixed this in latest pull request, and also fixed it in habit details too)

**Comment by ericbrisson** [comment]
Looks like these are fixed! We'll close the issue once the version with the fix for the Today page crash is pushed!
